# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acorta', '0002_auto_20160419_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.CharField(max_length=256)),
                ('short', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='Direcciones',
        ),
    ]
