# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acorta', '0003_auto_20160419_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='long',
            new_name='longurl',
        ),
        migrations.RenameField(
            model_name='urls',
            old_name='short',
            new_name='shorturl',
        ),
    ]
